project/project.webapp/Controllers/NoticeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using project.data.Abstract;
using project.webapp.Filters;
using project.webapp.Models;

namespace project.webapp.Controllers{
    [CustomAuthorize("3, 2, 1")]
    public class NoticeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public NoticeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

    public IActionResult NoticeEdit()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

project/project.webapp/Controllers/OrderController.cs
using System.Diagnostics;
using System.Drawing.Imaging;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using project.data.Abstract;
using project.entity;
using project.webapp.Filters;
using project.webapp.Models;
using project.webapp.Services;

namespace project.webapp.Controllers{
    [CustomAuthorize("3,2,1")]
    public class OrderController : Controller
    {
        private readonly ILogger<OrderController> _logger;
        private readonly IConfiguration _configuration;
        private readonly IOtherRepository _otherRepository;
        private readonly IOrderRepository _orderRepository;
        private int _PageSize => HttpContext.Session.GetInt32("PageSize") ?? 20;
        public OrderController(ILogger<OrderController> logger, IOtherRepository otherRepository, IOrderRepository orderRepository, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            _orderRepository = orderRepository;
            _otherRepository = otherRepository;
        }

        public IActionResult OrderHome()
        {
            return View();
        }

        public async Task<IActionResult> CreateOrder(string _selectedItemCode, string _selectedSubItemCode, int page = 1, int pageSize = 20)
        {
            var items = await _orderRepository.GetAllAsync(page, pageSize, _selectedItemCode, _selectedSubItemCode);
            var itemCategories = _orderRepository.GetItemCategories();

            int totalCount = _orderRepository.GetFilterItemCount(_selectedItemCode, _selectedSubItemCode);
            int totalPages = (int)Math.Ceiling((double)totalCount / pageSize);
            ViewBag.TotalPage = totalPages;
            ViewBag.CurrentPage = page;
            ViewData["PageSize"] = pageSize;
            HttpContext.Session.SetInt32("PageSize", pageSize);

            ViewBag.PageSizes = new List<int> { 10, 20, 30, 40 };

            ViewBag.SelectedItemCode = _selectedItemCode;
            ViewBag.SelectedSubItemCode = _selectedSubItemCode;

            bool useDynamicImage = _configuration.GetValue<bool>("UseDynamicImage");
            ViewBag.UseDynamicImage = useDynamicImage;

            var model = new OrderPlaceModel
            {
                Items = items,
                ItemCategories = itemCategories,
                TotalPages = totalPages,
                CurrentPage = page
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddToBasket(string pItemNo, decimal pQuantity, string pSalesDescription)
        {
            if (string.IsNullOrEmpty(pItemNo))
            {
                Console.WriteLine("Geçersiz veri!");
                return BadRequest("Geçersiz veri!");
            }
            else if (pQuantity <= 0) {
                Console.WriteLine("Lütfen geçerli adet sayısı giriniz!");
                return BadRequest("Lütfen geçerli adet sayısı giriniz!");
            }

            if (string.IsNullOrEmpty(pSalesDescription))
            {
                pSalesDescription = "-";
            }

            await NAVServer.InsertWebBasket(DateTime.Now, WebLoginUser.AuthId, pItemNo, pQuantity, pSalesDescription);
            
            return Ok("Ürün başarıyla sepete eklendi.");
        }

        [HttpGet]
        public JsonResult GetItemCategoriesByItemCode(string selectedItemCode, int page = 1)
        {
            var filteredCategories = _orderRepository.GetItemCategories(selectedItemCode);
            var items = _orderRepository.GetItemsByCategory(page, _PageSize, selectedItemCode, null);
            var totalCount = _orderRepository.GetFilterItemCount(selectedItemCode, null);
            var totalPages = (int)Math.Ceiling((double)totalCount / _PageSize);

            return Json(new
            {
                filteredItems = items,
                categories = filteredCategories,
                totalPages = totalPages,
                currentPage = page
            });
        }


        [HttpGet]
        public JsonResult GetItemsByCategory(string selectedItemCode, string selectedSubCategory)
        {
            int page = 1;

            var filteredItems = _orderRepository.GetItemsByCategory(page, _PageSize, selectedItemCode, selectedSubCategory);
            var totalCount = _orderRepository.GetFilterItemCount(selectedItemCode, selectedSubCategory);
            int totalPages = (int)Math.Ceiling((double)totalCount / _PageSize);

            return Json(new { items = filteredItems, totalPages = totalPages });
        }

        [HttpGet]
        public JsonResult GetItemsByCategoryPaged(string selectedItemCode, string selectedSubCategory, int page = 1)
        {
            var filteredItems = _orderRepository.GetItemsByCategory(page, _PageSize, selectedItemCode, selectedSubCategory);
            var totalCount = _orderRepository.GetFilterItemCount(selectedItemCode, selectedSubCategory);
            int totalPages = (int)Math.Ceiling((double)totalCount / _PageSize);

            return Json(new { items = filteredItems, totalPages = totalPages, currentPage = page });
        }

        [HttpGet]
        public JsonResult GetItemDetails(string itemCode)
        {
            var itemDetailList = _orderRepository.GetItemDetail(itemCode);
            var itemComponentList = _orderRepository.GetComponentsByItemNo(itemCode);
            return Json(new { itemDetailData = itemDetailList, itemComponentData = itemComponentList});
        }

        [HttpGet]
        public JsonResult GetAllFilterItems(string pItemCode, string pSalesDescription, string pAlternativeCode)
        {
            var filteredItems = _orderRepository.GetAll(1, _PageSize, pItemCode, pSalesDescription, pAlternativeCode);

            return Json(filteredItems);
        }

        public IActionResult Confirm(){
            var items = _orderRepository.GetBasketByUserId(0);
            return View(items);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmBasket()
        {
            await NAVServer.ConfirmWebBasket(WebLoginUser.AuthId);
            return RedirectToAction("CreateOrder");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBasketItem(DateTime pDateTime, string pItemNo)
        {
            await _orderRepository.DeleteItemFromBasket(pDateTime, pItemNo);
            return RedirectToAction("Confirm");
        }

        public IActionResult Control(){
            var items = _orderRepository.GetBasketByUserId(1);
            return View(items);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

project/project.webapp/Controllers/ReportController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using project.entity;
using project.webapp.Filters;
using project.webapp.Models;
using project.webapp.Services;

namespace project.webapp.Controllers{
    [CustomAuthorize("3,2,1")]
    public class ReportController : Controller
    {
        private readonly ILogger<ReportController> _logger;

        public ReportController(ILogger<ReportController> logger)
        {
            _logger = logger;
        }

        public IActionResult Mizan()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MizanCreateReport(DateTime pStartDate, DateTime pEndDate, string pFileType)
        {
            //pdf xlsx formatında gönderilecek
            var result = await NAVServer.CreateReport_50018(WebLoginUser.CustomerNo, pStartDate, pEndDate, pFileType);
            Console.WriteLine(result.success);

            byte[] fileBytes = Convert.FromBase64String(result.fileContent);
            return File(fileBytes, $"application/{pFileType}", $"{WebLoginUser.CustomerNo}-{pStartDate.ToString("yyyy-MM-dd")}-{pEndDate.ToString("yyyy-MM-dd")}.{pFileType}"); 
        }
        
        public IActionResult Ekstre()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EkstreCreateReport(DateTime pStartDate, DateTime pEndDate, string pFileType)
        {
            //pdf xlsx formatında gönderilecek
            var result = await NAVServer.CreateReport_50162(WebLoginUser.CustomerNo, pStartDate, pEndDate, pFileType);
            Console.WriteLine(result.success);

            byte[] fileBytes = Convert.FromBase64String(result.fileContent);
            return File(fileBytes, $"application/{pFileType}", $"{WebLoginUser.CustomerNo}-{pStartDate.ToString("yyyy-MM-dd")}-{pEndDate.ToString("yyyy-MM-dd")}.{pFileType}"); 
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

project/project.webapp/Views/Shared/Components/Category/Default.cshtml
<style>
    .dropdown:hover > .dropdown-menu {
        display: block;
    }

    .dropdown-submenu {
        position: relative;
    }

    .dropdown-submenu > .dropdown-menu {
        display: none;
        position: absolute;
        left: 100%;
        top: 0;
        margin-top: 0;
    }

    .dropdown-submenu:hover > .dropdown-menu {
        display: block;
    }

    .dropdown span:hover, .dropdown a:hover, .nav-item a:hover  {
        background-color: #eeeeee;
        padding: 6px 12px;
        border-radius: 4px;
        transition: background-color 0.5s ease, padding 0.3s ease;
    }
</style>

<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
</li>
@if(WebLoginUser.PageAuthorize.Siparis != false){
    <div class="dropdown">
        <a class="nav-link text-dark" asp-area="" asp-controller="Order"
            asp-action="CreateOrder">Sipariş</a>

        <ul class="dropdown-menu">
            @if(WebLoginUser.PageAuthorize.Siparis_Gec != false){
                <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Order"
                    asp-action="CreateOrder">Sipariş Geç</a></li>
            }
            @if(WebLoginUser.PageAuthorize.Siparis_Onayla != false){
                <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Order"
                    asp-action="Confirm">Sipariş Onayla</a></li>
            }
            @if(WebLoginUser.PageAuthorize.Siparis_Kontrol != false){
                <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Order"
                    asp-action="Control">Sipariş Kontrol</a></li>
            }
        </ul>
    </div>
}

@if(WebLoginUser.PageAuthorize.Islevler != false){
    <div class="dropdown">
        <a class="nav-link text-dark" asp-area="" asp-controller="Function"
        asp-action="SellOutEntry">İşlevler</a>

        <ul class="dropdown-menu">
            @if(WebLoginUser.PageAuthorize.Islevler_SellOutGiris != false){
                <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Function"
                    asp-action="SellOutEntry">Sell-out Giriş</a></li>
            }
            @if(WebLoginUser.PageAuthorize.Islevler_NumaratorGiris != false){
                <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Function"
                    asp-action="NumaratorEntry">Numaratör Giriş</a></li>
            }
            @if(WebLoginUser.PageAuthorize.Islevler_SeriKontrol != false){
                <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Function"
                    asp-action="SerialControl">Seri Kontrol</a></li>
            }
            @if(WebLoginUser.PageAuthorize.Islevler_Garanti != false){
                <li class="dropdown-submenu">
                    <a class="dropdown-item text-dark">Garanti</a>
                    <ul class="dropdown-menu">
                        @if(WebLoginUser.PageAuthorize.Islevler_Garanti_IstekGiris != false){
                            <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Function"
                        asp-action="WarrantyReqEntry">Garanti İstek Giriş</a></li>
                        }
                        @if(WebLoginUser.PageAuthorize.Islevler_Garanti_SurecTakip != false){
                            <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Function"
                        asp-action="WarrantyProcessTrack">Garanti Süreç Takibi</a></li>
                        }
                    </ul>
                </li>
            }
        </ul>
    </div>
}

@if(WebLoginUser.PageAuthorize.Raporlar != false){
    <div class="dropdown">
        <a class="nav-link text-dark" asp-area="" asp-controller="Report"
            asp-action="Mizan">Raporlar</a>

        <ul class="dropdown-menu">
            @if(WebLoginUser.PageAuthorize.Raporlar_Mizan != false){
                <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Report"
                    asp-action="Mizan">Mizan</a></li>
            }
            @if(WebLoginUser.PageAuthorize.Raporlar_Ekstre != false){
                <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Report"
                    asp-action="Ekstre">Ekstre</a></li>
            }
        </ul>
    </div>
}

@if(WebLoginUser.PageAuthorize.DuyuruDuzenle != false){
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Notice" asp-action="NoticeEdit">Duyuru Düzenle</a>
    </li>
}
@if(WebLoginUser.PageAuthorize.Download != false){
    <li class="nav-item">
        <a class="nav-link text-dark" href="ftp://bayii:2563@mbl.bilgitas.com.tr">Download</a>
    </li>
}


<ul class="navbar-nav ms-auto">
    <li class="nav-item"></li>
        <a class="nav-link text-dark">Hoşgeldiniz, @WebLoginUser.AuthId</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout"><span style="color: brown;">[Sistemden Çıkış]</span></a>
    </li>
</ul>