project/project.webapp/Controllers/FunctionController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using project.data.Abstract;
using project.entity;
using project.webapp.Filters;
using project.webapp.Models;
using System.IO;
using System.Collections.Generic;
using System.Threading.Tasks;
using ClosedXML.Excel;
using project.webapp.Services;  // ClosedXML kütüphanesini kullanıyoruz

namespace project.webapp.Controllers
{
    [CustomAuthorize("3, 2, 1")]
    public class FunctionController : Controller
    {
        private readonly ILogger<FunctionController> _logger;
        private readonly IOtherRepository _otherRepository;
        private readonly IFunctionRepository _functionRepository;

        public FunctionController(ILogger<FunctionController> logger, IFunctionRepository functionRepository, IOtherRepository otherRepository)
        {
            _logger = logger;
            _otherRepository = otherRepository;
            _functionRepository = functionRepository;
        }

        public IActionResult SellOutEntry(int page = 1)
        {
            int itemPerPage = 40;
            var items = _functionRepository.GetSellOutItems(page, itemPerPage);
            var keyvalueitems = _functionRepository.GetTaxAreas();
            
            int totalPage = _otherRepository.GetCountPerPage("Sell-out Ledger Entry", itemPerPage);
            ViewBag.TotalPage = totalPage;
            ViewBag.CurrentPage = page;

            var model = new SelloutModel{
                SellOutItems = items,
                KeyValueItems = keyvalueitems
            };

            return View(model);
        }

        public IActionResult SerialControl()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SerialControl(string pSerialNo = "")
        {
            if (string.IsNullOrEmpty(pSerialNo))
            {
                Console.WriteLine("Geçersiz veri!");
                return BadRequest("Geçersiz veri!");
            }
            var result = await NAVServer.FindItemSerial(WebLoginUser.AuthId, pSerialNo, WebLoginUser.CustomerNo); //burası konulacak mı 1 0 değerinde bi doğrulama dönüyor ancak veriye ihtiyaç var
            // var result = await NAVServer.FindItemSerial("STARGRUPBURO", "H564X49609", "B0000132"); //burası konulacak mı 1 0 değerinde bi doğrulama dönüyor ancak veriye ihtiyaç var
            
            if(result != 0){
                var item = _functionRepository.GetItemBySerialNo(pSerialNo);
                ViewBag.QuerySuccess = true;
                return View(item);
            }else{
                ViewBag.QuerySuccess = false;
                return View();
            }
        }

        public IActionResult NumaratorEntry()
        {
            var items = ViewData["NumeratorItems"] as List<NumeratorItem>;

            return View(items);
        }

        [HttpPost]
        public async Task<IActionResult> UploadExcel(IFormFile file)
        {
            List<NumeratorItem> numeratorItems = new List<NumeratorItem>();

            if (file != null && file.Length > 0)
            {
                // Dosyayı bir Stream'e kaydediyoruz
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    byte[] fileBytes = memoryStream.ToArray();

                    try
                    {
                        string tempFilePath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString() + ".xlsx");
                        System.IO.File.WriteAllBytes(tempFilePath, fileBytes);

                        using (var workbook = new XLWorkbook(tempFilePath))
                        {
                            
                            var worksheet = workbook.Worksheet(1);
                            
                            if(worksheet.Name != "NUMARATOR" && worksheet.Name != "NUMARATÖR" && worksheet.Name != ""){
                                RedirectToAction("NumaratorEntry");
                            }else{
                                int rowCount = worksheet.RowsUsed().Count();

                                for (int row = 2; row <= rowCount; row++)
                                {
                                    var numeratorItem = new NumeratorItem
                                    {
                                        BranchName = worksheet.Cell(row, 1).Value?.ToString(),
                                        InventoryNo = worksheet.Cell(row, 2).Value?.ToString(),
                                        ResponsibilityCenter = worksheet.Cell(row, 3).Value?.ToString(),
                                        ContractNo = worksheet.Cell(row, 4).Value?.ToString(),
                                        EndDate = DateOnly.TryParse(worksheet.Cell(row, 5).Value?.ToString() ?? "", out var endDate) ? endDate : default,
                                        ContractStatus = worksheet.Cell(row, 6).Value?.ToString(),
                                        ArticleNo = worksheet.Cell(row, 7).Value?.ToString(),
                                        Description = worksheet.Cell(row, 8).Value?.ToString(),
                                        SerialNo = worksheet.Cell(row, 9).Value?.ToString(),
                                        CurrentDefinition = worksheet.Cell(row, 10).Value?.ToString(),
                                        StockReading = worksheet.Cell(row, 11).Value?.ToString(),
                                        StockEntered = worksheet.Cell(row, 12).Value?.ToString(),
                                        StockDifference = worksheet.Cell(row, 13).Value?.ToString(),
                                        ColoredReading = worksheet.Cell(row, 14).Value?.ToString(),
                                        ColoredEntered = worksheet.Cell(row, 15).Value?.ToString(),
                                        ColoredDifference = worksheet.Cell(row, 16).Value?.ToString(),
                                        StockPrice = worksheet.Cell(row, 17).Value?.ToString(),
                                        RNKPrice = worksheet.Cell(row, 18).Value?.ToString(),
                                        InterventionTime = worksheet.Cell(row, 19).Value?.ToString(),
                                        ResolutionTime = worksheet.Cell(row, 20).Value?.ToString(),
                                        PeriodicMaintenanceTime = worksheet.Cell(row, 21).Value?.ToString(),
                                        Notes = worksheet.Cell(row, 22).Value?.ToString(),
                                        LaborCost = worksheet.Cell(row, 23).Value?.ToString(),
                                        ContractType = worksheet.Cell(row, 24).Value?.ToString(),
                                        ScopeType = worksheet.Cell(row, 25).Value?.ToString(),
                                        ScopeTypeDescription = worksheet.Cell(row, 26).Value?.ToString(),
                                        ServiceBlock = worksheet.Cell(row, 27).Value?.ToString(),
                                        MaterialBlock = worksheet.Cell(row, 28).Value?.ToString(),
                                        PenalClause = worksheet.Cell(row, 29).Value?.ToString(),
                                        CurrencyType = worksheet.Cell(row, 30).Value?.ToString(),
                                        ExchangeRate = worksheet.Cell(row, 31).Value?.ToString()
                                    };

                                    numeratorItems.Add(numeratorItem);
                                }

                            }

                        }
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "Hata: " + ex.Message;
                        return View();
                    }
                }

                return View("NumaratorEntry", numeratorItems); 
            }
            else
            {
                ViewBag.Message = "Geçerli bir dosya seçiniz.";
            }

            return RedirectToAction("NumaratorEntry");
        }

        public IActionResult WarrantyReqEntry()
        {
            return View();
        }

        public IActionResult WarrantyProcessTrack()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

project/project.webapp/Views/Function/SellOutEntry.cshtml
@model SelloutModel

@{
    ViewData["Title"] = "Sell Out Entry";

    int currentPage = ViewBag.CurrentPage ?? 1;
    int totalPages = ViewBag.TotalPage ?? 1;
    int pageRange = 10;
    int startPage = Math.Max(1, currentPage - (pageRange / 2));
    int endPage = Math.Min(totalPages, startPage + pageRange - 1);
}
<h1>@ViewData["Title"]</h1>

<div class="mb-3 row">
    <div class="col-3">
        <input type="file" class="form-control btn btn-secondary" name="file" id="file" /> @*Yerel Bölge Ayarlarına Göre Dil Değişimi Yapıyor !!!*@
    </div>
    <div class="col-3">
        <input type="submit" class="form-control btn btn-success" id="InputExcel" value="Excel'den Çek">
    </div>
</div>

<nav>
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link @(currentPage > 1 ? "" : "disabled")" href="@Url.Action("SellOutEntry", "Function", new { page = 1 })">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link @(currentPage > 1 ? "" : "disabled")" href="@Url.Action("SellOutEntry", "Function", new { page = currentPage - 1 })">&lt;</a>
        </li>

        @for (int i = startPage; i <= endPage; i++)
        {
            <li class="page-item @(i == currentPage ? "active" : "")">
                <a class="page-link" href="@Url.Action("SellOutEntry", "Function", new { page = i })">@i</a>
            </li>
        }
        <li class="page-item">
            <a class="page-link @(currentPage < totalPages ? "" : "disabled")" href="@Url.Action("SellOutEntry", "Function", new { page = currentPage + 1 })">&gt;</a>
        </li>
        <li class="page-item">
            <a class="page-link @(currentPage < totalPages ? "" : "disabled")" href="@Url.Action("SellOutEntry", "Function", new { page = totalPages })">&raquo;</a>
        </li>
    </ul>
</nav>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Madde No</th>
            <th scope="col">Seri No</th>
            <th scope="col">Bilgitaş Fatura No</th>
            <th scope="col">Bilgitaş Fatura Tarihi</th>
        </tr>
        <tr>
            <th scope="col" />
            <th scope="col"><input type="text" class="form-control"></th>
            <th scope="col"><input type="text" class="form-control"></th>
            <th scope="col" />
            <th scope="col" />
        </tr>
    </thead>
    <tbody>
        @try
        {
            foreach (var items in Model.SellOutItems)
            {
                <tr>
                    @* <td><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#sellOutEntryModal">Giriş</button></td> *@
                    <td>
                        <button type="button" class="btn btn-primary sellOutEntryBtn"
                            data-bs-toggle="modal" 
                            data-bs-target="#sellOutEntryModal"
                            data-itemno="@items.ItemNo"
                            data-serialno="@items.SerialNo"
                            data-invoiceno="@items.InvoiceNo"
                            data-invoicedate="@items.InvoiceDate">
                            Giriş
                        </button>
                    </td>
                    <td>@items.ItemNo</td>
                    <td>@items.SerialNo</td>
                    <td>@items.InvoiceNo</td>
                    <td>@items.InvoiceDate</td>
                </tr>
            }
        }
        catch
        {

        }
    </tbody>
</table>

<div class="modal fade" id="sellOutEntryModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="sellOutEntryModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Müşteri Bilgi Formu</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <!-- Müşteri Ünvan -->
                        <div class="col-4 mb-2">
                            <label for="musteriUnvan" class="form-label">Müşteri Ünvan</label>
                            <input type="text" class="form-control" id="musteriUnvan">
                        </div>

                        <!-- Müşteri Adresi -->
                        <div class="col-4 mb-2">
                            <label for="musteriAdresi" class="form-label">Müşteri Adresi</label>
                            <input type="text" class="form-control" id="musteriAdresi">
                        </div>

                        <!-- Müşteri Adresi 2 -->
                        <div class="col-4 mb-2">
                            <label for="musteriAdresi2" class="form-label">Müşteri Adresi 2</label>
                            <input type="text" class="form-control" id="musteriAdresi2">
                        </div>

                        <!-- Şehir -->
                        <div class="col-4 mb-2">
                            <label for="sehir" class="form-label">Şehir</label>
                            <input type="text" class="form-control" id="sehir">
                        </div>

                        <!-- Kamu Kuruluşu -->
                        <div class="col-4 mb-2">
                            <label for="kamuKurulusu" class="form-label">Kamu Kuruluşu</label>
                            <input type="checkbox" class="form-check-input" id="kamuKurulusu">
                        </div>

                        <!-- Müşteri Vergi Dairesi -->
                        <div class="col-4 mb-2">
                            <label for="musteriVergiDairesi" class="form-label">Müşteri Vergi Dairesi</label>
                            <select name="" id="">
                                @foreach(var item in Model.KeyValueItems){
                                    <option value="@item.Code">@item.Description</option>         
                                }
                            </select>
                        </div>

                        <!-- Müşteri Vergi/Kimlik No -->
                        <div class="col-4 mb-2">
                            <label for="musteriVergiNo" class="form-label">Müşteri Vergi/Kimlik No</label>
                            <input type="text" class="form-control" id="musteriVergiNo">
                        </div>

                        <!-- Müşteri Telefon No -->
                        <div class="col-4 mb-2">
                            <label for="musteriTelefon" class="form-label">Müşteri Telefon No</label>
                            <input type="number" class="form-control" id="musteriTelefon" placeholder="(___) ___ __ __">
                        </div>

                        <!-- Müşteri Faks No -->
                        <div class="col-4 mb-2">
                            <label for="musteriFaks" class="form-label">Müşteri Faks No</label>
                            <input type="text" class="form-control" id="musteriFaks">
                        </div>

                        <!-- Yetkili Adı Soyadı -->
                        <div class="col-4 mb-2">
                            <label for="yetkiliAdSoyad" class="form-label">Yetkili Adı Soyadı</label>
                            <input type="text" class="form-control" id="yetkiliAdSoyad">
                        </div>

                        <!-- Müşteri E-Mail Adresi -->
                        <div class="col-4 mb-2">
                            <label for="musteriEmail" class="form-label">Müşteri E-Mail Adresi</label>
                            <input type="email" class="form-control" id="musteriEmail">
                        </div>

                        <!-- Müşteri Web Adresi -->
                        <div class="col-4 mb-2">
                            <label for="musteriWeb" class="form-label">Müşteri Web Adresi</label>
                            <input type="url" class="form-control" id="musteriWeb">
                        </div>

                        <!-- Bayi Fatura Tarihi -->
                        <div class="col-4 mb-2">
                            <label for="bayiFaturaTarihi" class="form-label">Bayi Fatura Tarihi</label>
                            <input type="date" class="form-control" id="bayiFaturaTarihi">
                        </div>

                        <!-- Bayi Fatura No -->
                        <div class="col-4 mb-2">
                            <label for="bayiFaturaNo" class="form-label">Bayi Fatura No</label>
                            <input type="text" class="form-control" id="bayiFaturaNo">
                        </div>

                        <!-- Ürün Kuruluş Tarihi -->
                        <div class="col-4 mb-2">
                            <label for="urunKurulusTarihi" class="form-label">Ürün Kuruluş Tarihi</label>
                            <input type="date" class="form-control" id="urunKurulusTarihi">
                        </div>

                        <!-- Açıklama -->
                        <div class="col-4 mb-2">
                            <label for="aciklama" class="form-label">Açıklama</label>
                            <textarea class="form-control" id="aciklama" rows="3"></textarea>
                        </div>

                        <!-- Madde No -->
                        <div class="col-4 mb-2">
                            <label for="maddeNo" class="form-label">Madde No</label>
                            <input type="text" class="form-control" id="maddeNo" value="04YC4015" readonly>
                        </div>

                        <!-- Seri No -->
                        <div class="col-4 mb-2">
                            <label for="seriNo" class="form-label">Seri No</label>
                            <input type="text" class="form-control" id="seriNo" value="L4N2805589" readonly>
                        </div>

                        <!-- Bilgitaş Fatura No -->
                        <div class="col-4 mb-2">
                            <label for="maddeNo" class="form-label">Bilgitaş Fatura No</label>
                            <input type="text" class="form-control" id="faturaNo" value="697467" readonly>
                        </div>

                        <!-- Bilgitaş Fatura Tarihi -->
                        <div class="col-4 mb-2">
                            <label for="seriNo" class="form-label">Bilgitaş Fatura Tarihi</label>
                            <input type="date" class="form-control" id="faturaTarih" readonly>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                <button type="button" class="btn btn-primary">Kaydet</button>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    // Tüm detay butonlarını seç
    document.querySelectorAll(".sellOutEntryBtn").forEach(button => {
        button.addEventListener("click", function() {
            // Butondan data-attribute'ları al
            let itemNo = this.getAttribute("data-itemno");
            let serialNo = this.getAttribute("data-serialno");
            let invoiceNo = this.getAttribute("data-invoiceno");
            let invoiceDate = this.getAttribute("data-invoicedate");

            // Modal içindeki ilgili inputları doldur
            document.getElementById("maddeNo").value = itemNo;
            document.getElementById("seriNo").value = serialNo;
            document.getElementById("faturaNo").value = invoiceNo;
            document.getElementById("faturaTarih").value = invoiceDate;
        });
    });
});
</script>

project/project.webapp/Views/Function/SerialControl.cshtml
@model ItemSerial

@{
    ViewData["Title"] = "Seri Kontrol";

    var Success = ViewBag.QuerySuccess;
}
<h1>@ViewData["Title"]</h1>
<div class="pb-3">
    <form asp-controller="Function" asp-action="SerialControl" method="post">
        <div class="mb-3 row">
            <label for="InputSerialNumber" class="col-sm-2 col-form-label">Seri Numarasını Girin: </label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="pSerialNo" id="InputSerialNumber">
            </div>
            <div class="col-sm-2">
                <input type="submit" class="form-control btn btn-primary" id="InputQuery" value="Sorgula">
            </div>
        </div>
    </form>

    @if(Success != null){
        if(Success == true){
            <div class="row">
                <div class="col-5">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong>Madde Kodu:</strong>
                            <span>@Model.ItemNo</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong>Gönderi Tarihi:</strong>
                            <span>@Model.PostingDate</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong>Seri Numarası:</strong>
                            <span>@Model.SerialNo</span>
                        </li>
                    </ul>
                </div>
                <div class="col-5">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong>Açıklama</strong>
                            <span>@Model.Description</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong>Müşteri Numarası:</strong>
                            <span>@Model.CustomerNo</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong>Müşteri Adı:</strong>
                            <span>@Model.Name</span>
                        </li>
                    </ul>
                </div>
            </div>
        }else{
            <div class="alert alert-warning" role="alert">
                Sorguladığınız seri numarası bir Kyocera ürünü DEĞİLDİR!
            </div>
        }
    }
</div>

project/project.webapp/Views/Function/WarrantyReqEntry.cshtml
@{
    ViewData["Title"] = "Garanti İstek Girişi";

    bool IsTest = false;
}
<h1>@ViewData["Title"]</h1>
<div class="pb-3">
    <form asp-controller="Function" asp-action="WarrantyReqEntry" method="post">
        <div class="mb-3 row">
            <label for="InputSerialNumber" class="col-sm-2 col-form-label">Seri Numarasını Girin: </label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="SerialNo" id="InputSerialNumber">
            </div>
            <div class="col-sm-2">
                <input type="submit" class="form-control btn btn-primary" id="InputQuery" value="Bul">
            </div>
        </div>
    </form>

    @if (IsTest == true)
    {
        <div class="row">
            <div class="col-5">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <strong>Madde Kodu:</strong>
                        <span>@Model.ItemNo</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <strong>Gönderi Tarihi:</strong>
                        <span>@Model.PostingDate</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <strong>Seri Numarası:</strong>
                        <span>@Model.SerialNo</span>
                    </li>
                </ul>
            </div>
            <div class="col-5">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <strong>Açıklama</strong>
                        <span>@Model.Description</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <strong>Müşteri Numarası:</strong>
                        <span>@Model.CustomerNo</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <strong>Müşteri Adı:</strong>
                        <span>@Model.Name</span>
                    </li>
                </ul>
            </div>
        </div>
    }
    else
    {
        <div class="col-12">
            <div class="alert alert-warning" role="alert">
                <img src="~/error.png" alt="">
                <b>HATA: </b>Garanti isteği oluşturulamadı. Nedeni: {SERİNO} ürününün garanti süresi tanımlı değil!
                <button type="button" class="btn btn-secondary">Kapat</button>
            </div>
        </div>
    }
</div>